server:
  port: 8899
  tomcat:
      accesslog:
        buffered: true
        directory: F:\yxw\yxw_logs
        enabled: true
        file-date-format: .yyyy-MM-dd
        pattern: common
        prefix: access_log
        rename-on-rotate: false
        request-attributes-enabled: false
        rotate: true



spring:
#模板引擎
    thymeleaf:
        prefix: classpath:/templates/
    resources:
        static-locations: classpath:/static/,classpath:/public/
#mq中间件
    activemq:
        broker-url: tcp://192.168.0.197:61616  #根据自己服务器调整
        user: admin
        password: admin
        pool:
          enabled: false
#数据库连接
    datasource:
        name: test
        url: jdbc:mysql://118.31.9.5:3306/yxw_master01?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: niping
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20



## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.yxw.web.entity  # 注意：对应实体类的路径

